version: '3'

services:
  app:
    image: '8giggle-api:latest'
    build:
      context: ../../../
    container_name: app
    ports:
      - '9000:8080'
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=8giggle
      - POSTGRES_PASSWORD=8giggle