spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${PROD_JWT_SECRET}
cloudinary:
  api:
    secret: ${CLOUDINARY_SECRET}
    key: ${CLOUDINARY_KEY}
    name: ${CLOUDINARY_NAME}