spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/giggle
    username: postgres
    password: bUCLVLwih0C2a6H0sp!0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Configuration for enabling mock data insertion in development mode
app:
  development:
    mockdata:
      enabled: true